### ISSUE TITLE
Development Database Setup

### ISSUE THREAD

**Issue by msnilsen** [oswaldoelias/Military-Visualization-Developers#7]
Set up a database on a remote server (AWS EC2 free teir) which all team members can access. Share credentials for both read/write access and read/write/admin access.

**Comment by drgreer7** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Military-Visualization-Developers-60393391ddb23f0015a93ed8/issues/oswaldoelias/Military-Visualization-Developers/7?planning-poker) with ZenHub @DYSTCryptic @msnilsen @oswaldoelias @Sahej-Gill
